<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1">

<link href="data:text/css;charset=utf-8,%0A%40font%2Dface%20%7B%0Afont%2Dfamily%3A%20octicons%2Dlink%3B%0Asrc%3A%20url%28data%3Afont%2Fwoff%3Bcharset%3Dutf%2D8%3Bbase64%2Cd09GRgABAAAAAAZwABAAAAAACFQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABEU0lHAAAGaAAAAAgAAAAIAAAAAUdTVUIAAAZcAAAACgAAAAoAAQAAT1MvMgAAAyQAAABJAAAAYFYEU3RjbWFwAAADcAAAAEUAAACAAJThvmN2dCAAAATkAAAABAAAAAQAAAAAZnBnbQAAA7gAAACyAAABCUM%2B8IhnYXNwAAAGTAAAABAAAAAQABoAI2dseWYAAAFsAAABPAAAAZwcEq9taGVhZAAAAsgAAAA0AAAANgh4a91oaGVhAAADCAAAABoAAAAkCA8DRGhtdHgAAAL8AAAADAAAAAwGAACfbG9jYQAAAsAAAAAIAAAACABiATBtYXhwAAACqAAAABgAAAAgAA8ASm5hbWUAAAToAAABQgAAAlXu73sOcG9zdAAABiwAAAAeAAAAME3QpOBwcmVwAAAEbAAAAHYAAAB%2FaFGpk3jaTY6xa8JAGMW%2FO62BDi0tJLYQincXEypYIiGJjSgHniQ6umTsUEyLm5BV6NDBP8Tpts6F0v%2Bk%2F0an2i%2BitHDw3v2%2B9%2BDBKTzsJNnWJNTgHEy4BgG3EMI9DCEDOGEXzDADU5hBKMIgNPZqoD3SilVaXZCER3%2FI7AtxEJLtzzuZfI%2BVVkprxTlXShWKb3TBecG11rwoNlmmn1P2WYcJczl32etSpKnziC7lQyWe1smVPy%2FLt7Kc%2B0vWY%2FgAgIIEqAN9we0pwKXreiMasxvabDQMM4riO%2BqxM2ogwDGOZTXxwxDiycQIcoYFBLj5K3EIaSctAq2kTYiw%2Bymhce7vwM9jSqO8JyVd5RH9gyTt2%2BJ%2FyUmYlIR0s04n6%2B7Vm1ozezUeLEaUjhaDSuXHwVRgvLJn1tQ7xiuVv%2FocTRF42mNgZGBgYGbwZOBiAAFGJBIMAAizAFoAAABiAGIAznjaY2BkYGAA4in8zwXi%2BW2%2BMjCzMIDApSwvXzC97Z4Ig8N%2FBxYGZgcgl52BCSQKAA3jCV8CAABfAAAAAAQAAEB42mNgZGBg4f3vACQZQABIMjKgAmYAKEgBXgAAeNpjYGY6wTiBgZWBg2kmUxoDA4MPhGZMYzBi1AHygVLYQUCaawqDA4PChxhmh%2F8ODDEsvAwHgMKMIDnGL0x7gJQCAwMAJd4MFwAAAHjaY2BgYGaA4DAGRgYQkAHyGMF8NgYrIM3JIAGVYYDT%2BAEjAwuDFpBmA9KMDEwMCh9i%2Fv8H8sH0%2F4dQc1iAmAkALaUKLgAAAHjaTY9LDsIgEIbtgqHUPpDi3gPoBVyRTmTddOmqTXThEXqrob2gQ1FjwpDvfwCBdmdXC5AVKFu3e5MfNFJ29KTQT48Ob9%2FlqYwOGZxeUelN2U2R6%2BcArgtCJpauW7UQBqnFkUsjAY%2FkOU1cP%2BDAgvxwn1chZDwUbd6CFimGXwzwF6tPbFIcjEl%2BvvmM%2FbyA48e6tWrKArm4ZJlCbdsrxksL1AwWn%2FyBSJKpYbq8AXaaTb8AAHja28jAwOC00ZrBeQNDQOWO%2F%2FsdBBgYGRiYWYAEELEwMTE4uzo5Zzo5b2BxdnFOcALxNjA6b2ByTswC8jYwg0VlNuoCTWAMqNzMzsoK1rEhNqByEyerg5PMJlYuVueETKcd%2F89uBpnpvIEVomeHLoMsAAe1Id4AAAAAAAB42oWQT07CQBTGv0JBhagk7HQzKxca2sJCE1hDt4QF%2B9JOS0nbaaYDCQfwCJ7Au3AHj%2BLO13FMmm6cl7785vven0kBjHCBhfpYuNa5Ph1c0e2Xu3jEvWG7UdPDLZ4N92nOm%2BEBXuAbHmIMSRMs%2B4aUEd4Nd3CHD8NdvOLTsA2GL8M9PODbcL%2BhD7C1xoaHeLJSEao0FEW14ckxC%2BTU8TxvsY6X0eLPmRhry2WVioLpkrbp84LLQPGI7c6sOiUzpWIWS5GzlSgUzzLBSikOPFTOXqly7rqx0Z1Q5BAIoZBSFihQYQOOBEdkCOgXTOHA07HAGjGWiIjaPZNW13%2F%2Blm6S9FT7rLHFJ6fQbkATOG1j2OFMucKJJsxIVfQORl%2B9Jyda6Sl1dUYhSCm1dyClfoeDve4qMYdLEbfqHf3O%2FAdDumsjAAB42mNgYoAAZQYjBmyAGYQZmdhL8zLdDEydARfoAqIAAAABAAMABwAKABMAB%2F%2F%2FAA8AAQAAAAAAAAAAAAAAAAABAAAAAA%3D%3D%29%20format%28%27woff%27%29%3B%0A%7D%0Abody%20%7B%0A%2Dwebkit%2Dtext%2Dsize%2Dadjust%3A%20100%25%3B%0Atext%2Dsize%2Dadjust%3A%20100%25%3B%0Acolor%3A%20%23333%3B%0Afont%2Dfamily%3A%20%22Helvetica%20Neue%22%2C%20Helvetica%2C%20%22Segoe%20UI%22%2C%20Arial%2C%20freesans%2C%20sans%2Dserif%2C%20%22Apple%20Color%20Emoji%22%2C%20%22Segoe%20UI%20Emoji%22%2C%20%22Segoe%20UI%20Symbol%22%3B%0Afont%2Dsize%3A%2016px%3B%0Aline%2Dheight%3A%201%2E6%3B%0Aword%2Dwrap%3A%20break%2Dword%3B%0A%7D%0Aa%20%7B%0Abackground%2Dcolor%3A%20transparent%3B%0A%7D%0Aa%3Aactive%2C%0Aa%3Ahover%20%7B%0Aoutline%3A%200%3B%0A%7D%0Astrong%20%7B%0Afont%2Dweight%3A%20bold%3B%0A%7D%0Ah1%20%7B%0Afont%2Dsize%3A%202em%3B%0Amargin%3A%200%2E67em%200%3B%0A%7D%0Aimg%20%7B%0Aborder%3A%200%3B%0A%7D%0Ahr%20%7B%0Abox%2Dsizing%3A%20content%2Dbox%3B%0Aheight%3A%200%3B%0A%7D%0Apre%20%7B%0Aoverflow%3A%20auto%3B%0A%7D%0Acode%2C%0Akbd%2C%0Apre%20%7B%0Afont%2Dfamily%3A%20monospace%2C%20monospace%3B%0Afont%2Dsize%3A%201em%3B%0A%7D%0Ainput%20%7B%0Acolor%3A%20inherit%3B%0Afont%3A%20inherit%3B%0Amargin%3A%200%3B%0A%7D%0Ahtml%20input%5Bdisabled%5D%20%7B%0Acursor%3A%20default%3B%0A%7D%0Ainput%20%7B%0Aline%2Dheight%3A%20normal%3B%0A%7D%0Ainput%5Btype%3D%22checkbox%22%5D%20%7B%0Abox%2Dsizing%3A%20border%2Dbox%3B%0Apadding%3A%200%3B%0A%7D%0Atable%20%7B%0Aborder%2Dcollapse%3A%20collapse%3B%0Aborder%2Dspacing%3A%200%3B%0A%7D%0Atd%2C%0Ath%20%7B%0Apadding%3A%200%3B%0A%7D%0A%2A%20%7B%0Abox%2Dsizing%3A%20border%2Dbox%3B%0A%7D%0Ainput%20%7B%0Afont%3A%2013px%20%2F%201%2E4%20Helvetica%2C%20arial%2C%20nimbussansl%2C%20liberationsans%2C%20freesans%2C%20clean%2C%20sans%2Dserif%2C%20%22Apple%20Color%20Emoji%22%2C%20%22Segoe%20UI%20Emoji%22%2C%20%22Segoe%20UI%20Symbol%22%3B%0A%7D%0Aa%20%7B%0Acolor%3A%20%234078c0%3B%0Atext%2Ddecoration%3A%20none%3B%0A%7D%0Aa%3Ahover%2C%0Aa%3Aactive%20%7B%0Atext%2Ddecoration%3A%20underline%3B%0A%7D%0Ahr%20%7B%0Aheight%3A%200%3B%0Amargin%3A%2015px%200%3B%0Aoverflow%3A%20hidden%3B%0Abackground%3A%20transparent%3B%0Aborder%3A%200%3B%0Aborder%2Dbottom%3A%201px%20solid%20%23ddd%3B%0A%7D%0Ahr%3Abefore%20%7B%0Adisplay%3A%20table%3B%0Acontent%3A%20%22%22%3B%0A%7D%0Ahr%3Aafter%20%7B%0Adisplay%3A%20table%3B%0Aclear%3A%20both%3B%0Acontent%3A%20%22%22%3B%0A%7D%0Ah1%2C%0Ah2%2C%0Ah3%2C%0Ah4%2C%0Ah5%2C%0Ah6%20%7B%0Amargin%2Dtop%3A%2015px%3B%0Amargin%2Dbottom%3A%2015px%3B%0Aline%2Dheight%3A%201%2E1%3B%0A%7D%0Ah1%20%7B%0Afont%2Dsize%3A%2030px%3B%0A%7D%0Ah2%20%7B%0Afont%2Dsize%3A%2021px%3B%0A%7D%0Ah3%20%7B%0Afont%2Dsize%3A%2016px%3B%0A%7D%0Ah4%20%7B%0Afont%2Dsize%3A%2014px%3B%0A%7D%0Ah5%20%7B%0Afont%2Dsize%3A%2012px%3B%0A%7D%0Ah6%20%7B%0Afont%2Dsize%3A%2011px%3B%0A%7D%0Ablockquote%20%7B%0Amargin%3A%200%3B%0A%7D%0Aul%2C%0Aol%20%7B%0Apadding%3A%200%3B%0Amargin%2Dtop%3A%200%3B%0Amargin%2Dbottom%3A%200%3B%0A%7D%0Aol%20ol%2C%0Aul%20ol%20%7B%0Alist%2Dstyle%2Dtype%3A%20lower%2Droman%3B%0A%7D%0Aul%20ul%20ol%2C%0Aul%20ol%20ol%2C%0Aol%20ul%20ol%2C%0Aol%20ol%20ol%20%7B%0Alist%2Dstyle%2Dtype%3A%20lower%2Dalpha%3B%0A%7D%0Add%20%7B%0Amargin%2Dleft%3A%200%3B%0A%7D%0Acode%20%7B%0Afont%2Dfamily%3A%20Consolas%2C%20%22Liberation%20Mono%22%2C%20Menlo%2C%20Courier%2C%20monospace%3B%0Afont%2Dsize%3A%2012px%3B%0A%7D%0Apre%20%7B%0Amargin%2Dtop%3A%200%3B%0Amargin%2Dbottom%3A%200%3B%0Afont%3A%2012px%20Consolas%2C%20%22Liberation%20Mono%22%2C%20Menlo%2C%20Courier%2C%20monospace%3B%0A%7D%0A%2Eselect%3A%3A%2Dms%2Dexpand%20%7B%0Aopacity%3A%200%3B%0A%7D%0A%2Eocticon%20%7B%0Afont%3A%20normal%20normal%20normal%2016px%2F1%20octicons%2Dlink%3B%0Adisplay%3A%20inline%2Dblock%3B%0Atext%2Ddecoration%3A%20none%3B%0Atext%2Drendering%3A%20auto%3B%0A%2Dwebkit%2Dfont%2Dsmoothing%3A%20antialiased%3B%0A%2Dmoz%2Dosx%2Dfont%2Dsmoothing%3A%20grayscale%3B%0A%2Dwebkit%2Duser%2Dselect%3A%20none%3B%0A%2Dmoz%2Duser%2Dselect%3A%20none%3B%0A%2Dms%2Duser%2Dselect%3A%20none%3B%0Auser%2Dselect%3A%20none%3B%0A%7D%0A%2Eocticon%2Dlink%3Abefore%20%7B%0Acontent%3A%20%27%5Cf05c%27%3B%0A%7D%0A%2Emarkdown%2Dbody%3Abefore%20%7B%0Adisplay%3A%20table%3B%0Acontent%3A%20%22%22%3B%0A%7D%0A%2Emarkdown%2Dbody%3Aafter%20%7B%0Adisplay%3A%20table%3B%0Aclear%3A%20both%3B%0Acontent%3A%20%22%22%3B%0A%7D%0A%2Emarkdown%2Dbody%3E%2A%3Afirst%2Dchild%20%7B%0Amargin%2Dtop%3A%200%20%21important%3B%0A%7D%0A%2Emarkdown%2Dbody%3E%2A%3Alast%2Dchild%20%7B%0Amargin%2Dbottom%3A%200%20%21important%3B%0A%7D%0Aa%3Anot%28%5Bhref%5D%29%20%7B%0Acolor%3A%20inherit%3B%0Atext%2Ddecoration%3A%20none%3B%0A%7D%0A%2Eanchor%20%7B%0Adisplay%3A%20inline%2Dblock%3B%0Apadding%2Dright%3A%202px%3B%0Amargin%2Dleft%3A%20%2D18px%3B%0A%7D%0A%2Eanchor%3Afocus%20%7B%0Aoutline%3A%20none%3B%0A%7D%0Ah1%2C%0Ah2%2C%0Ah3%2C%0Ah4%2C%0Ah5%2C%0Ah6%20%7B%0Amargin%2Dtop%3A%201em%3B%0Amargin%2Dbottom%3A%2016px%3B%0Afont%2Dweight%3A%20bold%3B%0Aline%2Dheight%3A%201%2E4%3B%0A%7D%0Ah1%20%2Eocticon%2Dlink%2C%0Ah2%20%2Eocticon%2Dlink%2C%0Ah3%20%2Eocticon%2Dlink%2C%0Ah4%20%2Eocticon%2Dlink%2C%0Ah5%20%2Eocticon%2Dlink%2C%0Ah6%20%2Eocticon%2Dlink%20%7B%0Acolor%3A%20%23000%3B%0Avertical%2Dalign%3A%20middle%3B%0Avisibility%3A%20hidden%3B%0A%7D%0Ah1%3Ahover%20%2Eanchor%2C%0Ah2%3Ahover%20%2Eanchor%2C%0Ah3%3Ahover%20%2Eanchor%2C%0Ah4%3Ahover%20%2Eanchor%2C%0Ah5%3Ahover%20%2Eanchor%2C%0Ah6%3Ahover%20%2Eanchor%20%7B%0Atext%2Ddecoration%3A%20none%3B%0A%7D%0Ah1%3Ahover%20%2Eanchor%20%2Eocticon%2Dlink%2C%0Ah2%3Ahover%20%2Eanchor%20%2Eocticon%2Dlink%2C%0Ah3%3Ahover%20%2Eanchor%20%2Eocticon%2Dlink%2C%0Ah4%3Ahover%20%2Eanchor%20%2Eocticon%2Dlink%2C%0Ah5%3Ahover%20%2Eanchor%20%2Eocticon%2Dlink%2C%0Ah6%3Ahover%20%2Eanchor%20%2Eocticon%2Dlink%20%7B%0Avisibility%3A%20visible%3B%0A%7D%0Ah1%20%7B%0Apadding%2Dbottom%3A%200%2E3em%3B%0Afont%2Dsize%3A%202%2E25em%3B%0Aline%2Dheight%3A%201%2E2%3B%0Aborder%2Dbottom%3A%201px%20solid%20%23eee%3B%0A%7D%0Ah1%20%2Eanchor%20%7B%0Aline%2Dheight%3A%201%3B%0A%7D%0Ah2%20%7B%0Apadding%2Dbottom%3A%200%2E3em%3B%0Afont%2Dsize%3A%201%2E75em%3B%0Aline%2Dheight%3A%201%2E225%3B%0Aborder%2Dbottom%3A%201px%20solid%20%23eee%3B%0A%7D%0Ah2%20%2Eanchor%20%7B%0Aline%2Dheight%3A%201%3B%0A%7D%0Ah3%20%7B%0Afont%2Dsize%3A%201%2E5em%3B%0Aline%2Dheight%3A%201%2E43%3B%0A%7D%0Ah3%20%2Eanchor%20%7B%0Aline%2Dheight%3A%201%2E2%3B%0A%7D%0Ah4%20%7B%0Afont%2Dsize%3A%201%2E25em%3B%0A%7D%0Ah4%20%2Eanchor%20%7B%0Aline%2Dheight%3A%201%2E2%3B%0A%7D%0Ah5%20%7B%0Afont%2Dsize%3A%201em%3B%0A%7D%0Ah5%20%2Eanchor%20%7B%0Aline%2Dheight%3A%201%2E1%3B%0A%7D%0Ah6%20%7B%0Afont%2Dsize%3A%201em%3B%0Acolor%3A%20%23777%3B%0A%7D%0Ah6%20%2Eanchor%20%7B%0Aline%2Dheight%3A%201%2E1%3B%0A%7D%0Ap%2C%0Ablockquote%2C%0Aul%2C%0Aol%2C%0Adl%2C%0Atable%2C%0Apre%20%7B%0Amargin%2Dtop%3A%200%3B%0Amargin%2Dbottom%3A%2016px%3B%0A%7D%0Ahr%20%7B%0Aheight%3A%204px%3B%0Apadding%3A%200%3B%0Amargin%3A%2016px%200%3B%0Abackground%2Dcolor%3A%20%23e7e7e7%3B%0Aborder%3A%200%20none%3B%0A%7D%0Aul%2C%0Aol%20%7B%0Apadding%2Dleft%3A%202em%3B%0A%7D%0Aul%20ul%2C%0Aul%20ol%2C%0Aol%20ol%2C%0Aol%20ul%20%7B%0Amargin%2Dtop%3A%200%3B%0Amargin%2Dbottom%3A%200%3B%0A%7D%0Ali%3Ep%20%7B%0Amargin%2Dtop%3A%2016px%3B%0A%7D%0Adl%20%7B%0Apadding%3A%200%3B%0A%7D%0Adl%20dt%20%7B%0Apadding%3A%200%3B%0Amargin%2Dtop%3A%2016px%3B%0Afont%2Dsize%3A%201em%3B%0Afont%2Dstyle%3A%20italic%3B%0Afont%2Dweight%3A%20bold%3B%0A%7D%0Adl%20dd%20%7B%0Apadding%3A%200%2016px%3B%0Amargin%2Dbottom%3A%2016px%3B%0A%7D%0Ablockquote%20%7B%0Apadding%3A%200%2015px%3B%0Acolor%3A%20%23777%3B%0Aborder%2Dleft%3A%204px%20solid%20%23ddd%3B%0A%7D%0Ablockquote%3E%3Afirst%2Dchild%20%7B%0Amargin%2Dtop%3A%200%3B%0A%7D%0Ablockquote%3E%3Alast%2Dchild%20%7B%0Amargin%2Dbottom%3A%200%3B%0A%7D%0Atable%20%7B%0Adisplay%3A%20block%3B%0Awidth%3A%20100%25%3B%0Aoverflow%3A%20auto%3B%0Aword%2Dbreak%3A%20normal%3B%0Aword%2Dbreak%3A%20keep%2Dall%3B%0A%7D%0Atable%20th%20%7B%0Afont%2Dweight%3A%20bold%3B%0A%7D%0Atable%20th%2C%0Atable%20td%20%7B%0Apadding%3A%206px%2013px%3B%0Aborder%3A%201px%20solid%20%23ddd%3B%0A%7D%0Atable%20tr%20%7B%0Abackground%2Dcolor%3A%20%23fff%3B%0Aborder%2Dtop%3A%201px%20solid%20%23ccc%3B%0A%7D%0Atable%20tr%3Anth%2Dchild%282n%29%20%7B%0Abackground%2Dcolor%3A%20%23f8f8f8%3B%0A%7D%0Aimg%20%7B%0Amax%2Dwidth%3A%20100%25%3B%0Abox%2Dsizing%3A%20content%2Dbox%3B%0Abackground%2Dcolor%3A%20%23fff%3B%0A%7D%0Acode%20%7B%0Apadding%3A%200%3B%0Apadding%2Dtop%3A%200%2E2em%3B%0Apadding%2Dbottom%3A%200%2E2em%3B%0Amargin%3A%200%3B%0Afont%2Dsize%3A%2085%25%3B%0Abackground%2Dcolor%3A%20rgba%280%2C0%2C0%2C0%2E04%29%3B%0Aborder%2Dradius%3A%203px%3B%0A%7D%0Acode%3Abefore%2C%0Acode%3Aafter%20%7B%0Aletter%2Dspacing%3A%20%2D0%2E2em%3B%0Acontent%3A%20%22%5C00a0%22%3B%0A%7D%0Apre%3Ecode%20%7B%0Apadding%3A%200%3B%0Amargin%3A%200%3B%0Afont%2Dsize%3A%20100%25%3B%0Aword%2Dbreak%3A%20normal%3B%0Awhite%2Dspace%3A%20pre%3B%0Abackground%3A%20transparent%3B%0Aborder%3A%200%3B%0A%7D%0A%2Ehighlight%20%7B%0Amargin%2Dbottom%3A%2016px%3B%0A%7D%0A%2Ehighlight%20pre%2C%0Apre%20%7B%0Apadding%3A%2016px%3B%0Aoverflow%3A%20auto%3B%0Afont%2Dsize%3A%2085%25%3B%0Aline%2Dheight%3A%201%2E45%3B%0Abackground%2Dcolor%3A%20%23f7f7f7%3B%0Aborder%2Dradius%3A%203px%3B%0A%7D%0A%2Ehighlight%20pre%20%7B%0Amargin%2Dbottom%3A%200%3B%0Aword%2Dbreak%3A%20normal%3B%0A%7D%0Apre%20%7B%0Aword%2Dwrap%3A%20normal%3B%0A%7D%0Apre%20code%20%7B%0Adisplay%3A%20inline%3B%0Amax%2Dwidth%3A%20initial%3B%0Apadding%3A%200%3B%0Amargin%3A%200%3B%0Aoverflow%3A%20initial%3B%0Aline%2Dheight%3A%20inherit%3B%0Aword%2Dwrap%3A%20normal%3B%0Abackground%2Dcolor%3A%20transparent%3B%0Aborder%3A%200%3B%0A%7D%0Apre%20code%3Abefore%2C%0Apre%20code%3Aafter%20%7B%0Acontent%3A%20normal%3B%0A%7D%0Akbd%20%7B%0Adisplay%3A%20inline%2Dblock%3B%0Apadding%3A%203px%205px%3B%0Afont%2Dsize%3A%2011px%3B%0Aline%2Dheight%3A%2010px%3B%0Acolor%3A%20%23555%3B%0Avertical%2Dalign%3A%20middle%3B%0Abackground%2Dcolor%3A%20%23fcfcfc%3B%0Aborder%3A%20solid%201px%20%23ccc%3B%0Aborder%2Dbottom%2Dcolor%3A%20%23bbb%3B%0Aborder%2Dradius%3A%203px%3B%0Abox%2Dshadow%3A%20inset%200%20%2D1px%200%20%23bbb%3B%0A%7D%0A%2Epl%2Dc%20%7B%0Acolor%3A%20%23969896%3B%0A%7D%0A%2Epl%2Dc1%2C%0A%2Epl%2Ds%20%2Epl%2Dv%20%7B%0Acolor%3A%20%230086b3%3B%0A%7D%0A%2Epl%2De%2C%0A%2Epl%2Den%20%7B%0Acolor%3A%20%23795da3%3B%0A%7D%0A%2Epl%2Ds%20%2Epl%2Ds1%2C%0A%2Epl%2Dsmi%20%7B%0Acolor%3A%20%23333%3B%0A%7D%0A%2Epl%2Dent%20%7B%0Acolor%3A%20%2363a35c%3B%0A%7D%0A%2Epl%2Dk%20%7B%0Acolor%3A%20%23a71d5d%3B%0A%7D%0A%2Epl%2Dpds%2C%0A%2Epl%2Ds%2C%0A%2Epl%2Ds%20%2Epl%2Dpse%20%2Epl%2Ds1%2C%0A%2Epl%2Dsr%2C%0A%2Epl%2Dsr%20%2Epl%2Dcce%2C%0A%2Epl%2Dsr%20%2Epl%2Dsra%2C%0A%2Epl%2Dsr%20%2Epl%2Dsre%20%7B%0Acolor%3A%20%23183691%3B%0A%7D%0A%2Epl%2Dv%20%7B%0Acolor%3A%20%23ed6a43%3B%0A%7D%0A%2Epl%2Did%20%7B%0Acolor%3A%20%23b52a1d%3B%0A%7D%0A%2Epl%2Dii%20%7B%0Abackground%2Dcolor%3A%20%23b52a1d%3B%0Acolor%3A%20%23f8f8f8%3B%0A%7D%0A%2Epl%2Dsr%20%2Epl%2Dcce%20%7B%0Acolor%3A%20%2363a35c%3B%0Afont%2Dweight%3A%20bold%3B%0A%7D%0A%2Epl%2Dml%20%7B%0Acolor%3A%20%23693a17%3B%0A%7D%0A%2Epl%2Dmh%2C%0A%2Epl%2Dmh%20%2Epl%2Den%2C%0A%2Epl%2Dms%20%7B%0Acolor%3A%20%231d3e81%3B%0Afont%2Dweight%3A%20bold%3B%0A%7D%0A%2Epl%2Dmq%20%7B%0Acolor%3A%20%23008080%3B%0A%7D%0A%2Epl%2Dmi%20%7B%0Acolor%3A%20%23333%3B%0Afont%2Dstyle%3A%20italic%3B%0A%7D%0A%2Epl%2Dmb%20%7B%0Acolor%3A%20%23333%3B%0Afont%2Dweight%3A%20bold%3B%0A%7D%0A%2Epl%2Dmd%20%7B%0Abackground%2Dcolor%3A%20%23ffecec%3B%0Acolor%3A%20%23bd2c00%3B%0A%7D%0A%2Epl%2Dmi1%20%7B%0Abackground%2Dcolor%3A%20%23eaffea%3B%0Acolor%3A%20%2355a532%3B%0A%7D%0A%2Epl%2Dmdr%20%7B%0Acolor%3A%20%23795da3%3B%0Afont%2Dweight%3A%20bold%3B%0A%7D%0A%2Epl%2Dmo%20%7B%0Acolor%3A%20%231d3e81%3B%0A%7D%0Akbd%20%7B%0Adisplay%3A%20inline%2Dblock%3B%0Apadding%3A%203px%205px%3B%0Afont%3A%2011px%20Consolas%2C%20%22Liberation%20Mono%22%2C%20Menlo%2C%20Courier%2C%20monospace%3B%0Aline%2Dheight%3A%2010px%3B%0Acolor%3A%20%23555%3B%0Avertical%2Dalign%3A%20middle%3B%0Abackground%2Dcolor%3A%20%23fcfcfc%3B%0Aborder%3A%20solid%201px%20%23ccc%3B%0Aborder%2Dbottom%2Dcolor%3A%20%23bbb%3B%0Aborder%2Dradius%3A%203px%3B%0Abox%2Dshadow%3A%20inset%200%20%2D1px%200%20%23bbb%3B%0A%7D%0A%2Etask%2Dlist%2Ditem%20%7B%0Alist%2Dstyle%2Dtype%3A%20none%3B%0A%7D%0A%2Etask%2Dlist%2Ditem%2B%2Etask%2Dlist%2Ditem%20%7B%0Amargin%2Dtop%3A%203px%3B%0A%7D%0A%2Etask%2Dlist%2Ditem%20input%20%7B%0Amargin%3A%200%200%2E35em%200%2E25em%20%2D1%2E6em%3B%0Avertical%2Dalign%3A%20middle%3B%0A%7D%0A%3Achecked%2B%2Eradio%2Dlabel%20%7B%0Az%2Dindex%3A%201%3B%0Aposition%3A%20relative%3B%0Aborder%2Dcolor%3A%20%234078c0%3B%0A%7D%0A%2EsourceLine%20%7B%0Adisplay%3A%20inline%2Dblock%3B%0A%7D%0Acode%20%2Ekw%20%7B%20color%3A%20%23000000%3B%20%7D%0Acode%20%2Edt%20%7B%20color%3A%20%23ed6a43%3B%20%7D%0Acode%20%2Edv%20%7B%20color%3A%20%23009999%3B%20%7D%0Acode%20%2Ebn%20%7B%20color%3A%20%23009999%3B%20%7D%0Acode%20%2Efl%20%7B%20color%3A%20%23009999%3B%20%7D%0Acode%20%2Ech%20%7B%20color%3A%20%23009999%3B%20%7D%0Acode%20%2Est%20%7B%20color%3A%20%23183691%3B%20%7D%0Acode%20%2Eco%20%7B%20color%3A%20%23969896%3B%20%7D%0Acode%20%2Eot%20%7B%20color%3A%20%230086b3%3B%20%7D%0Acode%20%2Eal%20%7B%20color%3A%20%23a61717%3B%20%7D%0Acode%20%2Efu%20%7B%20color%3A%20%2363a35c%3B%20%7D%0Acode%20%2Eer%20%7B%20color%3A%20%23a61717%3B%20background%2Dcolor%3A%20%23e3d2d2%3B%20%7D%0Acode%20%2Ewa%20%7B%20color%3A%20%23000000%3B%20%7D%0Acode%20%2Ecn%20%7B%20color%3A%20%23008080%3B%20%7D%0Acode%20%2Esc%20%7B%20color%3A%20%23008080%3B%20%7D%0Acode%20%2Evs%20%7B%20color%3A%20%23183691%3B%20%7D%0Acode%20%2Ess%20%7B%20color%3A%20%23183691%3B%20%7D%0Acode%20%2Eim%20%7B%20color%3A%20%23000000%3B%20%7D%0Acode%20%2Eva%20%7Bcolor%3A%20%23008080%3B%20%7D%0Acode%20%2Ecf%20%7B%20color%3A%20%23000000%3B%20%7D%0Acode%20%2Eop%20%7B%20color%3A%20%23000000%3B%20%7D%0Acode%20%2Ebu%20%7B%20color%3A%20%23000000%3B%20%7D%0Acode%20%2Eex%20%7B%20color%3A%20%23000000%3B%20%7D%0Acode%20%2Epp%20%7B%20color%3A%20%23999999%3B%20%7D%0Acode%20%2Eat%20%7B%20color%3A%20%23008080%3B%20%7D%0Acode%20%2Edo%20%7B%20color%3A%20%23969896%3B%20%7D%0Acode%20%2Ean%20%7B%20color%3A%20%23008080%3B%20%7D%0Acode%20%2Ecv%20%7B%20color%3A%20%23008080%3B%20%7D%0Acode%20%2Ein%20%7B%20color%3A%20%23008080%3B%20%7D%0A" rel="stylesheet">
<style>
body {
  box-sizing: border-box;
  min-width: 200px;
  max-width: 980px;
  margin: 0 auto;
  padding: 45px;
  padding-top: 0px;
}
</style>

</head>

<body>

<h1 id="gender-pkg-nv-salary">Gender-Pkg-NV-Salary</h1>
<p>Maria Guideng</p>
<p>true</p>
<h2 id="application-of-gender-r-package-for-my-learning">Application of Gender R package for my learning</h2>
<p><strong>About</strong></p>
<p><a href="https://CRAN.R-project.org/package=gender">Gender</a> is an R package that predicts the gender of a name based on historical data. I'll explore this package as well as apply it to salary data provided by <a href="www.transparentnevada.com">NPRI</a> on Nevada public employees.</p>
<p>The input and output files are located in the <code>data</code> folder. In its original form, the input file <em>all-nevada-2016.csv</em> is obtained from a <a href="https://github.com/mguideng/Nevada-Public-Salaries">separate repository</a> and has 12 columns. The output file <em>all-nevada-2016-with-gender.csv</em> is the same, but has an additional column for employee gender. My contribution is the R script that adds this feature through the use of this package.</p>
<h2 id="exploring-whats-in-the-gender-package">Exploring what's in the gender package</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#install.packages(&quot;gender&quot;)</span>
<span class="kw">library</span>(gender)
<span class="kw">ls</span>(<span class="st">&quot;package:gender&quot;</span>)</code></pre></div>
<pre><code>TRUE [1] &quot;check_genderdata_package&quot;   &quot;gender&quot;                    
TRUE [3] &quot;gender_df&quot;                  &quot;install_genderdata_package&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#help(package = &quot;gender&quot;)</span></code></pre></div>
<p>After referencing the package's documentation and vignettes, I see that the basic function is <code>gender()</code>. One of its cool features is that it accounts for the fact that genders associated with names can change over time. Also, loading this package prompts you to install the <code>genderdata</code> package, which contains several datasets that permits the user to make predictions based on different time periods and geographical regions. As such, <code>gender()</code> allows you to choose a method to pass a set of names, places and birth years through the function.</p>
<p>Taken directly from the documentation, the basic usage is:</p>
<pre><code>gender(names, years = c(1932, 2012), method = c(&quot;ssa&quot;, &quot;ipums&quot;, &quot;napp&quot;,&quot;kantrowitz&quot;, &quot;genderize&quot;, 
&quot;demo&quot;),countries = c(&quot;United States&quot;, &quot;Canada&quot;,&quot;United Kingdom&quot;, &quot;Germany&quot;, &quot;Iceland&quot;, &quot;Norway&quot;, 
&quot;Sweden&quot;))</code></pre>
<p>...where <code>method</code> provides six options: * <strong>ssa</strong>: United States from 1930 to 2012. Drawn from Social Security Administration data. Option to select by state. * <strong>ipums</strong>: United States from 1789 to 1930. Drawn from Census data. * <strong>napp</strong>: Canada, the United Kingdom, Germany, Iceland, Norway, and Sweden for years between 1758 and 1910. * <strong>kantrowitz</strong>: 7,579 unique names compiled by Mark Kantrowitz in 1991. * <strong>genderize</strong>: based on &quot;user profiles across major social networks.&quot; * <strong>demo</strong>: Uses the top 100 names in the ssa method; provided for demonstration purposes (and not suitable for research purposes) when the <code>genderdata</code> package is not installed.</p>
<p>...and <code>countries</code> is the countries for which datasets are being used. For the: * &quot;ssa&quot; and &quot;ipums&quot; methods, the only valid option is <strong>United States</strong> which will be assumed if no argument is specified; * &quot;napp&quot; method, you may specify a character vector with: <strong>Canada</strong>, <strong>United Kingdom</strong>, <strong>Germany</strong>, <strong>Iceland</strong>, <strong>Norway</strong>, and <strong>Sweden</strong>; and * &quot;kantrowitz&quot; and &quot;genderize&quot; methods, no country should be specified.</p>
<p>If no method or years are specified, <code>gender()</code> will default to the ssa method for years 1932 - 2012. We'll keep things simple and go this route since it's the most suitable method for our salary data.</p>
<h2 id="bringing-in-other-packages-the-data">Bringing in other packages &amp; the data</h2>
<p><code>stringr</code> and <code>dplyr</code> will help to manipulate the names and summarize tabular data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#install.packages(c(&quot;stringr&quot;, &quot;dplyr&quot;))</span>
<span class="kw">library</span>(stringr)
<span class="kw">library</span>(dplyr)</code></pre></div>
<p>Next, we'll import the input file <em>all-nevada.2016.csv</em>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">salary &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;C:/Users/Rie Guide/Google Drive/NerdyRie/IP - GitHub/Repos/Gender-Pkg-NV-Salary/data/all-nevada-2016.csv&quot;</span>)</code></pre></div>
<p>Let's check it out!</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(salary)</code></pre></div>
<pre><code>## 'data.frame':    146662 obs. of  13 variables:
##  $ X                   : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ Employee.Name       : Factor w/ 144296 levels &quot;1 Undercover&quot;,..: 58744 122022 116480 32508 75772 55431 16607 64548 85294 140455 ...
##  $ Job.Title           : Factor w/ 12995 levels &quot;.INTERN I&quot;,&quot;.INTERN II&quot;,..: 2554 4528 4527 2530 5578 5570 4523 8888 2536 5570 ...
##  $ Base.Pay            : Factor w/ 94193 levels &quot;-16.75&quot;,&quot;-167.20&quot;,..: 6797 5530 93962 6099 6618 87234 3746 92101 2808 63289 ...
##  $ Overtime.Pay        : Factor w/ 36186 levels &quot;-0.12&quot;,&quot;-0.61&quot;,..: 12 12 12 12 12 18645 12 34664 12 8993 ...
##  $ Other.Pay           : Factor w/ 67988 levels &quot;-0.01&quot;,&quot;-0.02&quot;,..: 35143 37998 46402 20795 13034 28390 20550 36499 21157 50266 ...
##  $ Benefits            : Factor w/ 122187 levels &quot;-0.01&quot;,&quot;-0.29&quot;,..: 107841 96605 105651 105481 106128 105265 102829 100764 102830 104488 ...
##  $ Total.Pay           : num  161814 157783 146603 146044 144801 ...
##  $ Total.PayAndBenefits: num  215836 197927 197175 196394 196064 ...
##  $ Year                : int  2016 2016 2016 2016 2016 2016 2016 2016 2016 2016 ...
##  $ Notes               : Factor w/ 3 levels &quot;&quot;,&quot;Other Pay includes one-time retroactive payment.&quot;,..: NA NA NA NA NA NA NA NA NA NA ...
##  $ Agency              : Factor w/ 105 levels &quot;Boulder City&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...
##  $ Status              : Factor w/ 2 levels &quot;FT&quot;,&quot;PT&quot;: 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(salary,<span class="dv">5</span>)</code></pre></div>
<pre><code>##   X     Employee.Name                     Job.Title  Base.Pay Overtime.Pay
## 1 1      Jay D Fraser                  CITY MANAGER 130742.05            0
## 2 2    Scott P Hansen         DIRECTOR/PUBLIC WORKS  123417.9            0
## 3 3      Roger C Hall DIRECTOR/PARKS AND RECREATION  99300.74            0
## 4 4     David R Olsen                 CITY ATTORNEY  126717.8            0
## 5 5 Kevin D Nicholson                    FIRE CHIEF  129678.9            0
##   Other.Pay Benefits Total.Pay Total.PayAndBenefits Year Notes
## 1  31071.55 54022.18  161813.6             215835.8 2016  &lt;NA&gt;
## 2   34365.3 40143.36  157783.2             197926.6 2016  &lt;NA&gt;
## 3  47302.25 50571.52  146603.0             197174.5 2016  &lt;NA&gt;
## 4   19325.8  50349.9  146043.6             196393.5 2016  &lt;NA&gt;
## 5   15122.3 51263.28  144801.2             196064.5 2016  &lt;NA&gt;
##         Agency Status
## 1 Boulder City     FT
## 2 Boulder City     FT
## 3 Boulder City     FT
## 4 Boulder City     FT
## 5 Boulder City     FT</code></pre>
<p>There's a total of 146,662 employees. We're only interested in using the <code>Employee.Name</code> variable here. Since the names are combined, we'll need to parse out the vector of character strings.</p>
<h2 id="preparing-the-salary-data">Preparing the salary data</h2>
<p>Before passing the data through the gender function, it has to be prepped. The historical data of names within the package doesn't have any non-character symbols (e.g., digits, periods, hyphens, whitespace). It also uses lower title cases. Then we'll isolate the first names. The expected naming order convention is that the first name will be followed by the the middle and last names (&quot;maria guideng&quot;). It's also common to report the first name following a comma (&quot;guideng, maria&quot;). Our data should mimic these features. So those are three tasks so far.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Task 1. Remove non-characters. The order these are run is important.</span>

salary$Employee.Name &lt;-<span class="st"> </span><span class="kw">str_replace_all</span>(salary$Employee.Name, <span class="st">&quot;</span><span class="ch">\\</span><span class="st">d |</span><span class="ch">\\</span><span class="st">d&quot;</span>, <span class="st">&quot;&quot;</span>)  <span class="co"># Remove digits.</span>
salary$Employee.Name &lt;-<span class="st"> </span><span class="kw">gsub</span>(<span class="st">&quot;</span><span class="ch">\\</span><span class="st">.&quot;</span>, <span class="st">&quot; &quot;</span>, salary$Employee.Name)                 <span class="co"># Replace periods with a space.</span>
salary$Employee.Name &lt;-<span class="st"> </span><span class="kw">gsub</span>(<span class="st">&quot;-&quot;</span>, <span class="st">&quot; &quot;</span>, salary$Employee.Name)                   <span class="co"># Replace hypens with a space.</span>
salary$Employee.Name &lt;-<span class="st"> </span><span class="kw">gsub</span>(<span class="st">&quot;   &quot;</span>, <span class="st">&quot; &quot;</span>, salary$Employee.Name)                 <span class="co"># Remove triple spaces.</span>
salary$Employee.Name &lt;-<span class="st"> </span><span class="kw">gsub</span>(<span class="st">&quot;  &quot;</span>, <span class="st">&quot; &quot;</span>, salary$Employee.Name)                  <span class="co"># Remove double spaces.</span>

<span class="co"># Task 2. Isolate first names. If a comma is present in `Employee.Name` (&quot;guideng, maria&quot;), the first element of the string will be taken as `First.Name`. Otherwise (&quot;maria guideng&quot;), the first element of the string will be taken.</span>

salary$First.Name &lt;-<span class="st"> </span><span class="kw">sub</span>(<span class="st">&quot;.*</span><span class="ch">\\</span><span class="st">, &quot;</span>, <span class="st">&quot;&quot;</span>, salary$Employee.Name)  <span class="co"># If comma, take element following comma.</span>
salary$First.Name &lt;-<span class="st"> </span><span class="kw">sub</span>(<span class="st">&quot; .*&quot;</span>, <span class="st">&quot;&quot;</span>, salary$First.Name)        <span class="co"># Otherwise, just take first element.</span>


<span class="co"># Task 3. Lower case the first names.</span>
salary$First.Name &lt;-<span class="st"> </span><span class="kw">str_to_lower</span>(salary$First.Name)</code></pre></div>
<h2 id="ready-for-the-gender-function">Ready for the gender function</h2>
<p>Alas, let's run the gender function on the newly-created <code>First.Name</code> column.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">salary_gender &lt;-<span class="st"> </span><span class="kw">gender</span>(salary$First.Name)</code></pre></div>
<pre><code>## Warning: package 'bindrcpp' was built under R version 3.4.1</code></pre>
<p>It inferred the gender of 93% of the total employees (136,306 of 146,662 total). That's pretty good! Let's take a peek.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(salary_gender,<span class="dv">5</span>)</code></pre></div>
<pre><code>## # A tibble: 5 x 6
##   name  proportion_male proportion_female gender year_min year_max
##   &lt;chr&gt;           &lt;dbl&gt;             &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 aalya           0.                1.00  female    1932.    2012.
## 2 aamir           1.00              0.    male      1932.    2012.
## 3 aarin           0.564             0.436 male      1932.    2012.
## 4 aarin           0.564             0.436 male      1932.    2012.
## 5 aarin           0.564             0.436 male      1932.    2012.</code></pre>
<p>The gender function took a character vector of names and a range of years to predict the gender. Here, &quot;aalya&quot; has been proportionately all female, while &quot;aamir&quot; has undoubtedly been a male name. It's not so clear for the name &quot;aarin&quot; however, which has historically been nearly half and half: 56.4% being males and 43.6% females. However, it favors a male gender and is assigned as such.</p>
<p>We will join this to the main salary dataframe, so let's clean it up. Keep just the &quot;name&quot; and &quot;gender&quot; variables and rename them so they match the salary header names. Removing the duplicate names will also help make joining easier.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">salary_gender &lt;-<span class="st"> </span>salary_gender[<span class="kw">c</span>(<span class="st">&quot;name&quot;</span>, <span class="st">&quot;gender&quot;</span>)]
<span class="kw">colnames</span>(salary_gender) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;First.Name&quot;</span>, <span class="st">&quot;Gender&quot;</span>)
salary_gender &lt;-<span class="st"> </span><span class="kw">subset</span>(salary_gender, !<span class="kw">duplicated</span>(salary_gender$First.Name))</code></pre></div>
<p>Join it to the salary dataframe by <code>First.Name</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">salary &lt;-<span class="st"> </span><span class="kw">left_join</span>(salary, salary_gender)</code></pre></div>
<pre><code>## Joining, by = &quot;First.Name&quot;</code></pre>
<p>What's the distribution of males and females employees?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">salary %&gt;%
<span class="st">  </span><span class="kw">group_by</span>(Gender) %&gt;%
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">employees=</span><span class="kw">n</span>()) %&gt;%
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">percent=</span><span class="kw">round</span>((employees/<span class="kw">sum</span>(employees)*<span class="dv">100</span>))) %&gt;%
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(percent))</code></pre></div>
<pre><code>## # A tibble: 3 x 3
##   Gender employees percent
##   &lt;chr&gt;      &lt;int&gt;   &lt;dbl&gt;
## 1 female     77743     53.
## 2 male       58563     40.
## 3 &lt;NA&gt;       10356      7.</code></pre>
<p>Based on our work so far, women dominate the workforce when it comes to public service in Nevada. It's estimated to be at 53% but it would actually be more since it doesn't capture any of the 7% of workers whose gender is undetermined. Let's set them to &quot;undetm&quot; in our data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">salary$Gender[<span class="kw">is.na</span>(salary$Gender)] &lt;-<span class="st"> &quot;undetm&quot;</span></code></pre></div>
<p>Take a closer look and see what's going with the undetermined gender names by checking for patterns in the names and agencies. Can we do a better job?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">undetm &lt;-<span class="st"> </span>salary %&gt;%
<span class="st">  </span><span class="kw">filter</span>(Gender==<span class="st">&quot;undetm&quot;</span>) %&gt;%
<span class="st">  </span><span class="kw">group_by</span>(First.Name, Employee.Name, Agency) %&gt;%
<span class="st">  </span><span class="kw">summarize</span> (<span class="dt">n =</span> <span class="kw">n</span>()) %&gt;%
<span class="st">  </span><span class="kw">arrange</span>(-n)

<span class="kw">print</span>(undetm)</code></pre></div>
<pre><code>## # A tibble: 10,324 x 4
## # Groups:   First.Name, Employee.Name [10,292]
##    First.Name Employee.Name                           Agency             n
##    &lt;chr&gt;      &lt;chr&gt;                                   &lt;fct&gt;          &lt;int&gt;
##  1 redacted   Redacted Undercover Redacted Undercover Henderson         16
##  2 undercover Undercover                              Sparks             8
##  3 escamilla  ESCAMILLA MARTIN                        University Me~     2
##  4 gonzalez   GONZALEZ ANTHONY                        Clark County       2
##  5 gonzalez   GONZALEZ TOMAS                          Clark County       2
##  6 grana      GRANA JOHN                              Clark County       2
##  7 morales    MORALES JOSE                            Clark County       2
##  8 noi        PAPPAS, NOI                             Clark County       2
##  9 orozco     OROZCO ELIZABETH                        University Me~     2
## 10 sandoval   SANDOVAL SANDRA                         University Me~     2
## # ... with 10,314 more rows</code></pre>
<p>Which agencies have employees with the most undetermined genders?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">undetm %&gt;%
<span class="st">  </span><span class="kw">group_by</span>(Agency) %&gt;%
<span class="st">  </span><span class="kw">summarize</span> (<span class="dt">n =</span> <span class="kw">n</span>()) %&gt;%
<span class="st">  </span><span class="kw">arrange</span>(-n)</code></pre></div>
<pre><code>## # A tibble: 81 x 2
##    Agency                                n
##    &lt;fct&gt;                             &lt;int&gt;
##  1 Clark County                       2906
##  2 University Medical Center          2371
##  3 Clark County School District       1837
##  4 State of Nevada                     649
##  5 Washoe County School District       430
##  6 University of Nevada, Las Vegas     303
##  7 University of Nevada, Reno          293
##  8 Elko County                         213
##  9 Las Vegas Metro Police Department   191
## 10 Las Vegas                           134
## # ... with 71 more rows</code></pre>
<h2 id="fixing-undetermined-genders">Fixing undetermined genders</h2>
<p>After some poking around, here are the issues identified:</p>
<ol>
<li><p>First thing I noticed is that there's some names that are redacted or classified as being undercover. In these cases, keep them as is. Also, as expected, the package fails to make predictions for quite a bit of ethnic names, particularly for employees bearning names of Asian descent. We could look for a solution later, but we'll leave them as is for now.</p></li>
<li><p>Another issue is that University Medical Center reports employees using a different naming convention where last name is reported first without a comma preface (&quot;guideng maria&quot;). Clark County also does at times, but much less often than not. And while Clark County has the highest number of ambiguous names by count, it's also one of the largest agencies in that state with nearly 14,000 employees.</p></li>
<li>First names sometimes appear as suffixes (&quot;sr&quot;, &quot;iii&quot;, &quot;iv&quot;) such as for these folks:
<ul>
<li>&quot;sr timothy a maleport sr&quot;</li>
<li>&quot;iii carl william hart&quot;</li>
<li>&quot;iv joseph m schum&quot;</li>
</ul></li>
<li>Also, there's numerous instances where the first and last elements of <code>Employee.Name</code> are the same. For example,:
<ul>
<li>&quot;abarca daniel gonzalez abarca&quot;</li>
<li>&quot;kirgan marsha matsunaga kirgan&quot;</li>
<li>&quot;suarez juan r calvillo suarez&quot;</li>
</ul></li>
<li>Lastly, single-initial letters are being picked up as first names and that defies inferring a gender. E.g.,:
<ul>
<li>&quot;a elaine renta&quot;</li>
<li>&quot;m shane leavitt&quot;</li>
<li>&quot;p d ingram&quot;</li>
</ul></li>
</ol>
<p>Fortunately, the wrangling to fix issues 2 - 5 won't be so bad. It would be reasonable to adopt the second string of characters in <code>Employee.Name</code> as the first name in these cases, don't you think? It won't resolve them all, like for Mr.? or Ms.? P D Ingram, but it will help.</p>
<p>Ok, let's do it! First, some basic string split operations for later pattern matching functions.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">salary$stringcount &lt;-<span class="st"> </span><span class="kw">str_count</span>(salary$Employee.Name,<span class="st">&quot; &quot;</span>)+<span class="dv">1</span>                      <span class="co"># Count of all elements in string.</span>
salary$string1 &lt;-<span class="st"> </span><span class="kw">sapply</span>(<span class="kw">strsplit</span>(salary$Employee.Name, <span class="st">&quot; &quot;</span>), function(x) x[<span class="dv">1</span>])  <span class="co"># 1st string only.</span>
salary$string1len &lt;-<span class="st"> </span><span class="kw">nchar</span>(salary$string1)                                       <span class="co"># Length of 1st string.</span>
salary$string2 &lt;-<span class="st"> </span><span class="kw">sapply</span>(<span class="kw">strsplit</span>(salary$Employee.Name, <span class="st">&quot; &quot;</span>), function(x) x[<span class="dv">2</span>])  <span class="co"># 2nd string.</span>
salary$stringN &lt;-<span class="st"> </span><span class="kw">sapply</span>(<span class="kw">strsplit</span>(salary$Employee.Name, <span class="st">&quot; &quot;</span>), tail, <span class="dv">1</span>)           <span class="co"># Last string.</span>

<span class="co"># Fix issue 2. UMC reports last names first</span>
salary$First.Name &lt;-<span class="st"> </span><span class="kw">ifelse</span>(salary$Agency %in%<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;University Medical Center&quot;</span>), salary$string2, salary$First.Name)

<span class="co"># Fix issue 3. Suffix</span>
salary$First.Name &lt;-<span class="st"> </span><span class="kw">ifelse</span>(salary$First.Name %in%<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;jr&quot;</span>,<span class="st">&quot;sr&quot;</span>, <span class="st">&quot;ii&quot;</span>, <span class="st">&quot;iii&quot;</span>, <span class="st">&quot;iv&quot;</span>), salary$string2, salary$First.Name)

<span class="co"># Fix issue 4. First string = Last string</span>
salary$First.Name &lt;-<span class="st"> </span><span class="kw">ifelse</span>(salary$string1 ==<span class="st"> </span>salary$stringN &amp;<span class="st"> </span>salary$stringcount&gt;<span class="dv">1</span>, salary$string2, salary$First.Name)

<span class="co"># Fix issue 5. Initials. These are identified as those with `First.Name` having a length of 1 (basically, an initial) AND a count of 3+ elements in `Employee.Name`.</span>
salary$First.Name &lt;-<span class="st"> </span><span class="kw">ifelse</span>(salary$string1len ==<span class="st"> </span><span class="dv">1</span> &amp;<span class="st"> </span>salary$stringcount&gt;=<span class="dv">3</span>, salary$string2, salary$First.Name)</code></pre></div>
<h2 id="gender-function-round-2">Gender function, Round 2</h2>
<p>Ready to rerun that gender function on this updated salary dataframe.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">salary_gender &lt;-<span class="st"> </span><span class="kw">gender</span>(salary$First.Name)

<span class="co"># Again, just keep the &quot;name&quot; and &quot;gender&quot; variables and rename them, as well as remove the dupes.</span>
salary_gender &lt;-<span class="st"> </span>salary_gender[<span class="kw">c</span>(<span class="st">&quot;name&quot;</span>, <span class="st">&quot;gender&quot;</span>)]
<span class="kw">colnames</span>(salary_gender) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;First.Name&quot;</span>, <span class="st">&quot;Gender&quot;</span>)
salary_gender &lt;-<span class="st"> </span><span class="kw">subset</span>(salary_gender, !<span class="kw">duplicated</span>(salary_gender$First.Name))

<span class="co"># Now we can re-join it to the salary dataframe by `First.Name`, but first remove `Gender` from the previous run.</span>
salary$Gender &lt;-<span class="st"> </span><span class="ot">NULL</span>
salary &lt;-<span class="st"> </span><span class="kw">left_join</span>(salary, salary_gender)</code></pre></div>
<pre><code>## Joining, by = &quot;First.Name&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">salary$Gender[<span class="kw">is.na</span>(salary$Gender)] &lt;-<span class="st"> &quot;undetm&quot;</span></code></pre></div>
<p>Any better from that unknown 7%?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">table</span>(salary$Gender)</code></pre></div>
<pre><code>## 
## female   male undetm 
##  80935  57904   7823</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">prop.table</span>(<span class="kw">table</span>(salary$Gender))</code></pre></div>
<pre><code>## 
##     female       male     undetm 
## 0.55184710 0.39481256 0.05334033</code></pre>
<p>Yes, that's a bit better! Applying these fixes matched gender for another ~2,500 employees to 138,839 total employees. It's now down to 5% overall. How about on the agency level?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">undetm &lt;-<span class="st"> </span>salary %&gt;%
<span class="st">  </span><span class="kw">filter</span>(Gender==<span class="st">&quot;undetm&quot;</span>) %&gt;%
<span class="st">  </span><span class="kw">group_by</span>(First.Name, Employee.Name, Agency) %&gt;%
<span class="st">  </span><span class="kw">summarize</span> (<span class="dt">n =</span> <span class="kw">n</span>()) %&gt;%
<span class="st">  </span><span class="kw">arrange</span>(-n)

undetm %&gt;%
<span class="st">  </span><span class="kw">group_by</span>(Agency) %&gt;%
<span class="st">  </span><span class="kw">summarize</span> (<span class="dt">n =</span> <span class="kw">n</span>()) %&gt;%
<span class="st">  </span><span class="kw">arrange</span>(-n)</code></pre></div>
<pre><code>## # A tibble: 81 x 2
##    Agency                                n
##    &lt;fct&gt;                             &lt;int&gt;
##  1 Clark County                       2907
##  2 Clark County School District       1784
##  3 State of Nevada                     647
##  4 University Medical Center           444
##  5 University of Nevada, Las Vegas     228
##  6 Elko County                         213
##  7 University of Nevada, Reno          198
##  8 Las Vegas Metro Police Department   188
##  9 Washoe County School District       177
## 10 Las Vegas                           133
## # ... with 71 more rows</code></pre>
<p>There's improvements pretty much across the board for all agencies, especially with UMC.</p>
<p>Ok, so our last step is to revert back to the original structure of 12 columns, plus another column for <code>Gender</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">names</span>(salary)</code></pre></div>
<pre><code>##  [1] &quot;X&quot;                    &quot;Employee.Name&quot;        &quot;Job.Title&quot;           
##  [4] &quot;Base.Pay&quot;             &quot;Overtime.Pay&quot;         &quot;Other.Pay&quot;           
##  [7] &quot;Benefits&quot;             &quot;Total.Pay&quot;            &quot;Total.PayAndBenefits&quot;
## [10] &quot;Year&quot;                 &quot;Notes&quot;                &quot;Agency&quot;              
## [13] &quot;Status&quot;               &quot;First.Name&quot;           &quot;stringcount&quot;         
## [16] &quot;string1&quot;              &quot;string1len&quot;           &quot;string2&quot;             
## [19] &quot;stringN&quot;              &quot;Gender&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">salary &lt;-<span class="st"> </span>salary[, -<span class="kw">c</span>(<span class="dv">13</span>:<span class="dv">18</span>)]   <span class="co"># delete columns 13 through 18</span></code></pre></div>
<h2 id="output">Output</h2>
<p>Success. It's now ready for export.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">write.csv</span>(salary, <span class="st">&quot;all-Nevada-2016-with-gender.csv&quot;</span>)</code></pre></div>
<p><strong>Output dimensions</strong></p>
<table>
<colgroup>
<col width="11%"></col>
<col width="6%"></col>
<col width="8%"></col>
<col width="73%"></col>
</colgroup>
<thead>
<tr class="header">
<th>File</th>
<th>Total Rows</th>
<th>Total Columns</th>
<th>Columns</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>all-Nevada-2016-with-gender.csv</td>
<td>146,662</td>
<td>13</td>
<td>Employee.Name, Job.Title, Base.Pay, Overtime.Pay, Other.Pay, Benefits, Total.Pay, Total.PayBenefits, Year, Notes, Agency, Status, Gender</td>
</tr>
</tbody>
</table>
<p><strong>Exploration ideas</strong> * How many women work in government versus men and for which agencies? * How is pay different between men and women by job titles?</p>
<p><strong>Project purposes</strong> * Adding a gender column using Gender, an R package. * Being new to R, suggestions for improvement are appreciated.</p>

</body>
</html>
